<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Project: Finding Cananda!</title>
    </head>
    <style>
        body {
        background-color: blue;
        }
        
        
    </style>
    
    
    <body>
        <h1 align="center">Traveling to Canada!</h1>
        <h2 align="center"></h2>
    </body>
</html>
